//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.branchinventories = new HashSet<BranchInventory>();
            this.employees = new HashSet<Employee>();
        }
    
        public int branch_id { get; set; }
        public string branch_name { get; set; }
        public string branch_tel { get; set; }
        public string branch_add { get; set; }
    
        public virtual ICollection<BranchInventory> branchinventories { get; set; }
        public virtual ICollection<Employee> employees { get; set; }
    }
}
