//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int event_id { get; set; }
        public int event_type { get; set; }
        public Nullable<System.DateTime> event_timestamp { get; set; }
        public string event_message { get; set; }
        public string Employee_emp_id { get; set; }
        public int Employee_Branch_branch_id { get; set; }
    
        public virtual Employee employee { get; set; }
    }
}
