//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class good
    {
        public good()
        {
            this.branchinventories = new HashSet<branchinventory>();
            this.shippingdetails = new HashSet<shippingdetail>();
        }
    
        public int goods_id { get; set; }
        public string goods_name { get; set; }
        public string goods_price { get; set; }
        public int Model_mod_id { get; set; }
        public int Model_Brand_brand_id { get; set; }
        public string goods_img { get; set; }
    
        public virtual ICollection<branchinventory> branchinventories { get; set; }
        public virtual model model { get; set; }
        public virtual ICollection<shippingdetail> shippingdetails { get; set; }
    }
}
