//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class model
    {
        public model()
        {
            this.goods = new HashSet<good>();
        }
    
        public int mod_id { get; set; }
        public string mod_name { get; set; }
        public int Brand_brand_id { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual ICollection<good> goods { get; set; }
    }
}
